### ISSUE TITLE
11/18 話し合うこと

### ISSUE THREAD

**Issue by akaimo** [akaimo/iidaPro-2015#34]
時間があまりないので、効率化のため何か疑問点などがあれば書き込んでください。  
- クレジットの場所
  - 開発者にアクセスする方法もいるかも？
- DBのバージョン管理のやり方
- 天気api
- 分別方法（検索）の詳細画面は全て出すのか

**Comment by kariotoko** [comment]
・豆知識で写真がないものはどうするのか
・

**Comment by HIRAI-Tatsuhito** [comment]
・分別の方法の画面について、分別ごとの一般的注意（ペットボトルなら、「ラベルをはがして洗っておきましょう」的な文章）を表示するか
