### ISSUE TITLE
アイコン

### ISSUE THREAD

**Issue by akaimo** [akaimo/iidaPro-2015#52]
- トップのデカアイコン
  - 出すごみがない日のぶんも忘れずに
  - 小物金属とかと、かぶってるのも
- メニューアイコンの線の太さ
- 検索の基本的なごみ以外のアイコン
  - その他とか出せないとか?

**Comment by akaimo** [comment]
- トップのデカアイコンのない日とかぶってる日
- 検索とカレンダーのかぶってる日

あとはこれだけかな？

**Comment by NECKBEARD0624** [comment]
完了いたしました！
