### ISSUE TITLE
[注目]カレンダーの仕様について

### ISSUE THREAD

**Issue by akaimo** [akaimo/iidaPro-2015#65]
カレンダーを作る上で確認したいことがある。
- 当日が画面に真ん中で、当日を中心とした一ヶ月なのか（当日の上下に15日ずつある）、ただ単に今月を出すのか
- 今月以外の表示はどうするのか
  - 来月以降は、一日から表示するのか
  - 今月と同じ表示方法で月が変わっただけか
    - 今日が10日だとしたら、今月のカレンダーには先月の25日から今月の25日までだとしたら、これを引き継ぐ

言葉だとあやふやなところがあるから、今日が何日だとして、今月のカレンダーには何日から何日まで、来月のカレンダーには...
って感じで答えて欲しいです！

以下、決定事項
- ごみの分別アイコンを表示
- 縦型のカレンダー
- 当日が真ん中で少し大きく
- マイアラームのタイトル表示

**Comment by kariotoko** [comment]
当日を中心とした前後15日
来月に移った後は月を変えて前後15日
