### ISSUE TITLE
打ち合わせで聞くこと

### ISSUE THREAD

**Issue by akaimo** [akaimo/iidaPro-2015#67]
忘れないように書き込んでおきましょう。

**Comment by NECKBEARD0624** [comment]
ごみの写真を使う際に、その写真にごみのパッケージなどに企業名が映っても大丈夫なのかどうか

**Comment by akaimo** [comment]
トップに表示する地域名は区までではなく、町まで表示するか

**Comment by akaimo** [comment]
イベント情報の扱いについて
- どのような方法でデータを扱うか
- どのぐらいの情報量を表示するか
